---
- name: Deploy ONTAP Cluster config
  hosts: localhost
  roles:
    - role: /etc/ansible/lod-ansible-12/cluster

- name: Mount export to rhel
  hosts: rhel
  roles:  
    - role: /etc/ansible/lod-ansible-12/mount_nfs